name: Workflow for Codecov
on:
  push:
    paths:
      - 'adt/**'
      - 'tests/**'
      - '.github/**'
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6

    - name: Install Python requirements
      run: pip install -r requirements.txt

    - name: Collect coverage
      run: |
        coverage run --source=adt -m pytest
        coverage report
        coverage xml -o cov.xml --include=adt/__init__.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: cov.xml
        fail_ci_if_error: true
